version: '3.7'
services:
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
